### ISSUE TITLE
Stop printing redirect URL

### ISSUE THREAD

**Issue by mkaput** [software-mansion/asdf-scarb#11]
### Problem

It happens that we break output from some commands by printing the redirect URL 😱 I think it'd be the easiest if we drop it entirely, but we would very appreciate it if it could be conditionally printed during normal installation.

### Steps

```
$ asdf latest --all
elixir	main-otp-26	missing
erlang	26.0.2	missing
nodejs	20.5.1	missing
python	stackless-3.7.5	missing
ruby	truffleruby+graalvm-23.0.0	missing
redirect url: https://github.com/software-mansion/scarb/releases/tag/v0.6.2
scarb	0.6.2	installed
terraform	1.5.5	missing
```

### Notes

Please leave a comment that you are willing to contribute a PR fixing this issue before starting doing so, in order to avoid having two people working on this independently 😄 

### Does this issue reproduce in the latest version of asdf-scarb?

- [X] Yes, it does.

**Comment by gaetbout** [comment]
Can I try this one?

**Comment by mkaput** [comment]
Sure, go on, but perhaps wait for https://github.com/software-mansion/asdf-scarb/pull/10 to be merged :)

**Comment by gaetbout** [comment]
I subscribed to #10, I'll wait then :)
