### ISSUE TITLE
download scarb: The requested URL returned error: 404

### ISSUE THREAD

**Issue by MPSxDev** [software-mansion/asdf-scarb#22]
### Problem

Issue with generating release files that are not the same as the releases https://github.com/software-mansion/scarb/releases/

```
$ asdf install scarb 2.8.2
* Downloading scarb release 2.8.2...
curl: (22) The requested URL returned error: 404
asdf-scarb: Could not download https://github.com/software-mansion/scarb/releases/download/v2.8.2/scarb-v2.8.2-x86_64-pc-windows-gnu.tar.gz
```

### Steps

1. asdf install scarb 2.8.2 or any other version 

### Possible Solution(s)

URL generator needs to be updated

### Does this issue reproduce in the latest version of asdf-scarb?

- [X] Yes, it does.

**Comment by maciektr** [comment]
Hi @MPSxDev ! 
What OS are you using? 🤔

**Comment by MPSxDev** [comment]
Windows 11

**Comment by maciektr** [comment]
@MPSxDev ASDF is just written in Shell scripts. It does not support Windows. Your best shot is using ASDF in WSL2 (WSL1 is not supported) but only in linux directories - not Windows ones. See ASDF support for more info: https://asdf-vm.com/more/faq.html#wsl2-support For Windows, you should stick to downloading exe files manually.
