### ISSUE TITLE
Experiment with printing compatible Starknet versions in `asdf list-all scarb`

### ISSUE THREAD

**Issue by mkaput** [software-mansion/asdf-scarb#6]
From Slack conversation with @amanusk:
> Just on the last point,
> Is there some way we can easily use asdf to print out the scarb version and the starknet version?
> When doing list-all or such?
> maybe it doesn't quite make sense for starknet-less scarb
> But we need some way for devs to see what goes with what

I think values outputted from list-all implementation script are used in many places, not only for presentation, but nonetheless that’s a cool idea to investigate.

**Comment by szymmis** [comment]
Not feasible due to limitations of `asdf list-all` command related to whitespaces and autocompletion.

**Comment by szymmis** [comment]
After consultations with @amanusk, there will be 3 Starknet aliases: `starknet-mainnet`, `starknet-testnet` and `starknet-integration` for each of the Starknet networks

**Comment by AngelicaOvesdotter** [comment]
> From Slack conversation with @amanusk:
> > Just on the last point,
> > Is there some way we can easily use asdf to print out the scarb version and the starknet version?
> > When doing list-all or such?
> > maybe it doesn't quite make sense for starknet-less scarb
> > But we need some way for devs to see what goes with what
> 
> I think values outputted from list-all implementation script are used in many places, not only for presentation, but nonetheless that’s a cool idea to investigate.

![image](https://github.com/user-attachments/assets/2a34b100-aa96-47ca-974d-6469b1e052fa)![image](https://github.com/user-attachments/assets/478ad6c3-81bb-492d-80f2-5809be16c346)
